### ISSUE TITLE
Handynotes not work

### ISSUE THREAD

**Issue by jessy22003** [zarillion/handynotes-plugins#80] opened 2021-01-09 23:44 UTC
Hello 

unfortunately I’m able to see anything on either map from the addon. I tried reinstalling all of the apps, any suggestions? Thanks in advance.

**Comment by zarillion** [comment] 2021-02-07 21:45
Closing due to lack of information. Make sure you have both HandyNotes (base addon) and HandyNotes: Shadowlands installed. Try disabling all other addons to eliminate any potential conflicts as the cause.

**Closed as completed by zarillion** 2021-02-07 21:45 UTC
