### ISSUE TITLE
Missing Node Coords

### ISSUE THREAD

**Issue by Meebsy** [zarillion/handynotes-plugins#27] opened 2020-11-10 21:28 UTC
`1x ...faceHandyNotes_BattleForAzeroth\core\map.lua:86: No parent coords for node: 9235255 <EMPChest object at 0000023AB39882A0> 1530
[string "=[C]"]: in function `error'
[string "@HandyNotes_BattleForAzeroth\core\map.lua"]:86: in function `AddNode'
[string "@HandyNotes_BattleForAzeroth\core\map.lua"]:43: in function <...faceHandyNotes_BattleForAzeroth\core\map.lua:42>
[string "@HandyNotes_BattleForAzeroth\zones\vale.lua"]:568: in main chunk

Locals:
(*temporary) = "No parent coords for node: 9235255 <EMPChest object at 0000023AB39882A0> 1530`

`1x ...faceHandyNotes_BattleForAzeroth\core\map.lua:86: No parent coords for node: 9235255 <EMPChest object at 0000023AACC2F770> 1530
[string "=[C]"]: in function `error'
[string "@HandyNotes_BattleForAzeroth\core\map.lua"]:86: in function `AddNode'
[string "@HandyNotes_BattleForAzeroth\core\map.lua"]:43: in function <...faceHandyNotes_BattleForAzeroth\core\map.lua:42>
[string "@HandyNotes_BattleForAzeroth\zones\vale.lua"]:568: in main chunk

Locals:
(*temporary) = "No parent coords for node: 9235255 <EMPChest object at 0000023AACC2F770> 1530"
`
Running v1

**Comment by zarillion** [comment] 2020-11-10 21:39
I cannot reproduce this. When does the error occur and does it happen consistently? What version of HandyNotes are you using?

**Comment by Meebsy** [comment] 2020-11-10 23:09
Happens on loading into the game, and reloading the UI. Doesn't seem to cause adverse issues though.
Also get a bunch of null errors at the same time too, not sure if its related.

**Comment by Meebsy** [comment] 2020-11-10 23:40
I tried disabling all other handynote addons and other addons that did similiar things and it still showed up.

**Comment by Meebsy** [comment] 2020-11-11 08:36
Running HandyNotes v1.6.0 and v13 of Shadowlands and error is still showing up.
Don't have the time right now, but tomorrow for me I can try disabling one addon after another till it stops to find a possible culprit addon.

**Comment by dmartinzar** [comment] 2020-11-11 14:23
I can change that message from an error to a warning, but before I do that I am definitely curious why you are experience this but I'm not getting any other reports of it. Let me know if it happens with *only* HandyNotes and this plugin enabled. If it does, maybe we can dig into what makes your character or account special. I plan to use this child => parent coord feature a lot in the future.

**Comment by zarillion** [comment] 2020-11-11 14:37
I can change that message from an error to a warning, but before I do that I am definitely curious why you are experiencing this but I'm not getting any other reports of it. Let me know if it happens with only HandyNotes and this plugin enabled. If it does, maybe we can dig into what makes your character or account special. I plan to use this child => parent coord feature a lot in the future.

*Edit: reposting under correct account =)*

**Comment by Meebsy** [comment] 2020-11-12 08:10
I've found the culprit addon. It is ElvUI_Klix. It is in need of a code cleanup of which the author has said he will get too soon.
I'll let them know of what is going on with their addon and hopefully they can come up with a fix of sorts.

**Comment by Meebsy** [comment] 2020-11-13 04:20
Very odd, I commented out the node that it was referring too and the errors stops.
Considering it refers to a Black Empire chest and that event isn't up this week, could that be a factor in the cause of the error?

**Comment by zarillion** [comment] 2020-11-13 04:21
I thought you mentioned disabling the ElvUI_Klix addon resolves the issue? For everyone else, the map functions appear to be able to translation that coordinate correctly.

**Comment by Meebsy** [comment] 2020-11-13 04:28
I did disable it but it is a major component of my UI.
I have been in contact with its Author to find a possible fix.

**Comment by zarillion** [comment] 2020-11-15 03:45
I'm going to close this issue for now since it appears to be a problem for ElvUI_Klix to fix. I have not received any other reports of this error from others using the addon.

**Closed as completed by zarillion** 2020-11-15 03:45 UTC
