### ISSUE TITLE
Inconsistency with "appearance learned from other items" and "Show unobtainable transmog"

### ISSUE THREAD

**Issue by Le-Lucien** [zarillion/handynotes-plugins#169] opened 2022-04-11 13:19 UTC
Hello,

Sorry if it feels similar to #143 but there's some inconsistency with the appearance learned from other items when the option Show unobtainable transmog is turned on. There's no distinction between "unlearnable (known)" and "unlearnable (missing)". Resulting in a different display when playing different classes :
![HN](https://user-images.githubusercontent.com/102592187/162747804-f0b13ff8-eb3a-4ebe-8d7c-b9e2242a94fe.png)

**Comment by zarillion** [comment] 2022-04-11 17:34
I'm using this function to determine if the character knows the appearance. If they do, it will display "Known" before deciding to display "Unlearnable" or "Unobtainable".

```lua
function Transmog:IsKnown()
    if CTC.PlayerHasTransmog(self.item) then return true end
    local appearanceID, sourceID = CTC.GetItemInfo(self.item)
    if sourceID and CTC.PlayerHasTransmogItemModifiedAppearance(sourceID) then
        return true
    end
    if appearanceID then
        local sources = CTC.GetAppearanceSources(appearanceID)
        if sources then
            for i, source in pairs(sources) do
                if source.isCollected then return true end
            end
        end
    end
    return false
end
```

On my paladin, all of those functions return `false` for the Fang of Phestis, so even though I technically know the appearance, all of Blizzard's APIs say that I do not when on my paladin. I'm going to close this issue as "working as intended" since I have no control over what the Blizzard APIs return. I'm sorry I could not address it easily.

**Closed as completed by zarillion** 2022-04-11 17:34 UTC

**Comment by Le-Lucien** [comment] 2022-04-12 13:24
No worries. Thanks for your time !
