### ISSUE TITLE
Error: attempt to concatenate a nil value

### ISSUE THREAD

**Issue by rpvela** [zarillion/handynotes-plugins#213] opened 2022-11-29 03:05 UTC
Using version v4 of the addon. The repro steps are to hover over icons that require a certain Dragonscale Expedition level 

```lua
Message: ...erface/AddOns/HandyNotes_Dragonflight/core/nodes.lua:285: attempt to concatenate a nil value
Time: Tue Nov 29 03:05:01 2022
Count: 1
Stack: ...erface/AddOns/HandyNotes_Dragonflight/core/nodes.lua:285: attempt to concatenate a nil value
[string "@Interface/AddOns/HandyNotes_Dragonflight/core/nodes.lua"]:285: in function `Render'
[string "@Interface/AddOns/HandyNotes_Dragonflight/core/core.lua"]:116: in function <...terface/AddOns/HandyNotes_Dragonflight/core/core.lua:115>

Locals: self = <table> {
 _prepared = true
 note = "The required item can be found at Renown 21 with the Dragonscale Expedition in in Expedition Scout's Packs and Disturbed Dirts."
 requires = <table> {
 }
 glow = <table> {
 }
 __address = "000001AA741E6A50"
 rewards = <table> {
 }
 quest = <table> {
 }
 __class = <table> {
 }
}
tooltip = GameTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestPartyProgress = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessLineData = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:303
 SetPvpTalent = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRuneforgeResultItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetHyperlink = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnit = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetAzeriteEssence = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidDepositItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidWithdrawalItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 waitingForData = false
 OnLoad = <function> defined @Interface/FrameXML/GameTooltip.lua:927
 SetInfoBackdropStyle = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:338
 info = <table> {
 }
 shoppingTooltips = <table> {
 }
 SetSocketGem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 updateTooltipTimer = 0.043000
 ItemTooltip = Frame {
 }
 StatusBar = GameTooltipStatusBar {
 }
 SetLootCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetSlottedKeystone = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetWorldCursor = <function> defined @Interface/FrameXML/GameTooltip.lua:952
 SetLootItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetMerchantCostItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 GetUnit = <function> defined @Interface/FrameXML/GameTooltip.lua:994
 SetOwnedItemByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetItemInteractionItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestLogSpecialItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 TextRight1 = GameTooltipTextRight1 {
 }
 SetEnhancedConduit = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRecipeReagentItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 supportsDataRefresh = true
 SetWeeklyReward = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetMerchantItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetPvpBrawl = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetAchievementByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 BottomOverlay = Texture {
 }
 SetSpellByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 supportsItemComparison = true
 SetSocketedRelic = <function> defined @```

**Comment by ljlevend** [comment] 2022-11-29 18:14
Message: ...erface/AddOns/HandyNotes_Dragonflight/core/nodes.lua:285: attempt to concatenate a nil value
Time: Tue Nov 29 12:12:22 2022
Count: 1
Stack: ...erface/AddOns/HandyNotes_Dragonflight/core/nodes.lua:285: attempt to concatenate a nil value

Locals:

**Comment by Roneasaurus** [comment] 2022-11-30 02:59
15x HandyNotes_Dragonflight/core/nodes.lua:285: attempt to concatenate a nil value
[string "@HandyNotes_Dragonflight/core/nodes.lua"]:285: in function `Render'
[string "@HandyNotes_Dragonflight/core/core.lua"]:116: in function <HandyNotes_Dragonflight/core/core.lua:115>

Locals:
self = <table> {
 _prepared = true
 note = "The required item can be found at Renown 21 with the Dragonscale Expedition in in Expedition Scout's Packs and Disturbed Dirts."
 requires = <table> {
 }
 glow = <table> {
 }
 __address = "000001F2E39EDF10"
 rewards = <table> {
 }
 quest = <table> {
 }
 __class = <table> {
 }
}
tooltip = GameTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ItemTooltip = Frame {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidDepositItem = <function> defined =[C]:-1
 SetTraitEntry = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLootCurrency = <function> defined =[C]:-1
 SetWorldCursor = <function> defined @FrameXML/GameTooltip.lua:952
 SetLootItem = <function> defined =[C]:-1
 GetSpell = <function> defined @FrameXML/GameTooltip.lua:990
 SetQuestLogSpecialItem = <function> defined =[C]:-1
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 BottomOverlay = Texture {
 }
 SetSocketedRelic = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:236
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined =[C]:-1
 SetUnitDebuffByAuraInstanceID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetBagItem = <function> defined =[C]:-1
 AddLineDataText = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:324
 SetSpellBookItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ZGV_ShowManyLines = <function> defined @ZygorGuidesViewer/Functions.lua:362
 textLeft1Font = "GameTooltipHeaderText"
 SetShapeshift = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 hasMoney = 1
 SetArtifactPowerByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 SetSocketedItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnitDebuff = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetMountBySpellID = <function> defined =[C]:-1
 SetTrainerService = <function> defined =[C]:-1
 TextLeft1 = GameTooltipTextLeft1 {
 }
 SetAzeritePower = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLFGDungeonShortageReward = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetArtifactItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 StatusBar = GameTooltipStatusBar {
 }
 SetPossession = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnitAura = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnitBuffByAuraInstanceID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetConduit = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetMinimapMouseover = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 GetItem = <function> defined @FrameXML/GameTooltip.lua:986
 SetRecipeResultItem = <function> defined =[C]:-1
 SetQuestPartyProgress = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessLineData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:303
 SetText = <function> defined =[C]:-1
 SetPvpTalent = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRuneforgeResultItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnit = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetTotem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 SetInfoBackdr






i am also having this ussue

**Comment by jte369** [comment] 2022-11-30 05:55
Having this issue also, when hovering over items which require Dragonscale Expedition levels
Message: ...erface/AddOns/HandyNotes_Dragonflight/core/nodes.lua:285: attempt to concatenate a nil value
Time: Wed Nov 30 00:52:29 2022
Count: 5
Stack: ...erface/AddOns/HandyNotes_Dragonflight/core/nodes.lua:285: attempt to concatenate a nil value

Locals:

**Comment by lqnrd** [comment] 2022-11-30 08:33
Some quests from beta seem not to exist on live servers.

For example this one: https://www.wowhead.com/beta/quest=70833/rumors-of-the-jeweled-whelplings does not exist on live.

In file requirements.lua `function Quest:GetText() return C_QuestLog.GetTitleForQuestID(self.id) end` returns `nil` because `C_QuestLog.GetTitleForQuestID(70833)` returns nil, and then `text = color(L['Requires'] .. ' ' .. req:GetText())`of course throws an error.

### Quick fix for now

Open file `requirements.lua` and change line 140 from

    function Quest:GetText() return C_QuestLog.GetTitleForQuestID(self.id) end

to

    function Quest:GetText() return C_QuestLog.GetTitleForQuestID(self.id) or format("(unknown quest, fix pls: %d)", self.id or 0) end

**Comment by Krovikan** [comment] 2022-11-30 10:45
Thanks for the reports.

The issue is solved and in the following hours there will be a new version with the fix.


Regards

**Comment by Krovikan** [comment] 2022-11-30 17:36
HandyNotes: Dragonflight v5 is on line.

I close this issue.


Regards

**Closed as completed by Krovikan** 2022-11-30 17:36 UTC
