### ISSUE TITLE
Uldum and Vale Assults

### ISSUE THREAD

**Issue by cwwood0322** [zarillion/handynotes-plugins#49] opened 2020-11-20 17:30 UTC
There is an issue where the boundaries of the assaults' are messed up like currently on the map of the Vale you see the boundary for the Black Empire Assault, but you still see the boundary of the Mogu assault too. There is a similar issue in Uldum right now too.

**Comment by zarillion** [comment] 2020-11-20 18:09
Can you provide screenshots? It does not appear this way for me on retail right now. If the issue is still happening, see if disabling all other addons fixes it, and attach a list of those other addons if it does.

**Comment by zarillion** [comment] 2020-11-27 17:22
Closing this, not enough info to proceed.

**Closed as completed by zarillion** 2020-11-27 17:22 UTC
