### ISSUE TITLE
Rare icon colors appear wrong

### ISSUE THREAD

**Issue by KyrosKrane** [zarillion/handynotes-plugins#79] opened 2021-01-08 04:08 UTC
Just spotted this today while touring Maldraxxus:
![image](https://user-images.githubusercontent.com/458727/103973220-8bc49e80-5134-11eb-8db3-9a4107d838da.png)

Tahonta has a white skull on the minimap, but he has a drop I need and can use (the mount). Traditionally, this would use the purple skull icon

The purple skull next to him is Smorgas the Feaster. He's correctly purple. Tooltip for comparison:

![image](https://user-images.githubusercontent.com/458727/103973304-c0385a80-5134-11eb-9b83-6ed69ee96735.png)

**Comment by KyrosKrane** [comment] 2021-01-08 04:09
And just to complete the icon possibilities, to show that white skulls sometimes are correct:
![image](https://user-images.githubusercontent.com/458727/103973404-fa096100-5134-11eb-8113-4a5281a58176.png)

**Comment by zarillion** [comment] 2021-01-08 04:18
Are you a Necrolord?

**Comment by KyrosKrane** [comment] 2021-01-08 04:31
No, I'm Kyrian.

**Comment by zarillion** [comment] 2021-01-08 04:32
The Tahonta mount will only drop for Necrolords, which is why it has the Necrolord icon next to it. The missing mount will only cause the rare to appear as a blue skull for players of the Necrolord covenant. The Valfir, Harika and Hopecrusher rares also behave this way with their covenant-specific mount drops.

**Comment by KyrosKrane** [comment] 2021-01-08 06:35
In that case, shouldn't the mount appear as unobtainable, similar to the offhand in this pic?
![image](https://user-images.githubusercontent.com/458727/103982602-6726f180-5149-11eb-9f6b-6a78c1c7f4cc.png)

**Comment by zarillion** [comment] 2021-01-08 08:15
Thats a good suggestion! I'll consider making that change to make it more clear. For now I'm going to close this ticket since the rare icon appears to be working as intended.

**Closed as completed by zarillion** 2021-01-08 08:15 UTC
