### ISSUE TITLE
Elemental Storms tracking is highly inconsistent / incomplete

### ISSUE THREAD

**Issue by ghost** [zarillion/handynotes-plugins#346] opened 2023-05-21 02:33 UTC
Hello,

I wanted to re-open the issue about elemental storms but I do not have a way to do so.
Here is a link - im not sure if my comments notify you in any way as it is a closed topic. :)
https://github.com/zarillion/handynotes-plugins/issues/316

Thank you!

**Comment by Krovikan** [comment] 2023-05-21 09:05
Hello @Rezy942 . Yes, we have a channel in our discord that notifies all movements in Github (comments, issues open and close, lint, commits, etc). We can read part of your comments in this channel. ;-)

But is better that, make a new ticket instead search an old issue. I'll do a warning to coders. Thank you!

Regards

**Comment by Krovikan** [comment] 2023-05-22 23:04
Closed as duplicate of #316

**Closed as completed by Krovikan** 2023-05-22 23:04 UTC
